kind: Service
apiVersion: v1
metadata: 
  name: backend
  namespace: expense
spec:
  selector: #labels re used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080
